import * as THREE from 'three';
function rng(seed){return()=>{seed|=0;seed=seed+0x6D2B79F5|0;let t=Math.imul(seed^seed>>>15,1|seed);t=t+Math.imul(t^t>>>7,61|t)^t;return((t^t>>>14)>>>0)/4294967296;};}
export class DirtPatch{
 constructor(spec,scene,saved){Object.assign(this,spec);this.wet=0;this.progress=0;this.done=false;this.strokes=saved?.strokes||[];const c=this.canvas=document.createElement('canvas');c.width=c.height=256;const ctx=this.ctx=c.getContext('2d',{willReadFrequently:true});let r=rng([...this.id].reduce((n,c)=>n+c.charCodeAt(0),0));
  // An irregular transparent decal leaves the underlying material visible.
  if(this.kind==='dust'){for(let i=0;i<500;i++){const a=r()*Math.PI*2,rad=Math.sqrt(r()),x=128+Math.cos(a)*rad*111,y=128+Math.sin(a)*rad*107;ctx.fillStyle=`rgba(${76+Math.floor(r()*33)},${66+Math.floor(r()*30)},${51+Math.floor(r()*26)},${.13+r()*.28})`;ctx.beginPath();ctx.ellipse(x,y,1+r()*5,1+r()*2,r()*6,0,Math.PI*2);ctx.fill();}for(let i=0;i<20;i++){ctx.strokeStyle='rgba(44,44,33,.6)';ctx.lineWidth=.8;ctx.beginPath();let x=25+r()*200,y=25+r()*200;ctx.moveTo(x,y);ctx.quadraticCurveTo(x+15,y-8,x+20,y+13);ctx.stroke();}}
  else if(this.kind==='mud'){for(let j=0;j<5;j++){let x=75+(j%2)*86,y=27+j*44;ctx.save();ctx.translate(x,y);ctx.rotate(j%2?.2:-.25);ctx.fillStyle='rgba(83,65,43,.65)';ctx.beginPath();ctx.ellipse(0,0,18,27,0,0,7);ctx.fill();ctx.fillRect(-13,32,26,13);ctx.globalCompositeOperation='destination-out';for(let k=0;k<6;k++)ctx.fillRect(-18,-20+k*8,36,3);ctx.restore();}}
  else {for(let i=0;i<80;i++){const x=40+r()*176,y=40+r()*176,rad=12+r()*47;let grad=ctx.createRadialGradient(x,y,0,x,y,rad);const rgb=this.kind==='soap'?'86,109,89':'115,80,36';grad.addColorStop(0,`rgba(${rgb},.16)`);grad.addColorStop(.6,`rgba(${rgb},.1)`);grad.addColorStop(1,`rgba(${rgb},0)`);ctx.fillStyle=grad;ctx.fillRect(x-rad,y-rad,rad*2,rad*2);}for(let i=0;i<40;i++){ctx.fillStyle=this.kind==='soap'?'rgba(53,81,58,.23)':'rgba(111,77,31,.26)';ctx.beginPath();ctx.arc(30+r()*196,30+r()*196,1+r()*3,0,7);ctx.fill();}}
  this.initial=this.mass();const tex=this.texture=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const material=new THREE.MeshStandardMaterial({map:tex,transparent:true,depthWrite:false,roughness:.94,polygonOffset:true,polygonOffsetFactor:-1,side:THREE.DoubleSide});this.mesh=new THREE.Mesh(new THREE.PlaneGeometry(spec.w,spec.h),material);this.mesh.position.set(spec.x,spec.y,spec.z);this.mesh.rotation.x=spec.rotation;this.mesh.receiveShadow=true;this.mesh.userData.patch=this;scene.add(this.mesh);this.wet=saved?.wet||0;
  if(saved?.done){this.done=true;this.progress=1;this.mesh.visible=false;}else{for(const s of this.strokes)this.erase(...s,false);this.measure();}
 }
 mass(){let px=this.ctx.getImageData(0,0,256,256).data,sum=0;for(let i=3;i<px.length;i+=4)sum+=px[i];return sum;}
 measure(){this.progress=Math.max(0,1-this.mass()/this.initial);if(this.progress>.955){this.done=true;this.progress=1;this.mesh.visible=false;}return this.progress;}
 erase(u,v,radius,opacity,record=true){const c=this.ctx;c.save();c.globalCompositeOperation='destination-out';const x=u*256,y=(1-v)*256,rx=radius/this.w*256,ry=radius/this.h*256;c.translate(x,y);c.scale(rx,ry);const grad=c.createRadialGradient(0,0,0,0,0,1);grad.addColorStop(0,`rgba(0,0,0,${opacity})`);grad.addColorStop(.65,`rgba(0,0,0,${opacity})`);grad.addColorStop(1,'rgba(0,0,0,0)');c.fillStyle=grad;c.fillRect(-1,-1,2,2);c.restore();this.texture.needsUpdate=true;if(record){this.strokes.push([+u.toFixed(3),+v.toFixed(3),+radius.toFixed(3),+opacity.toFixed(3)]);if(this.strokes.length%8===0)this.measure();}}
 spray(dt){this.wet=Math.min(1,this.wet+dt*.48);this.mesh.material.roughness=.94-this.wet*.56;this.mesh.material.color.setRGB(1-this.wet*.12,1-this.wet*.08,1-this.wet*.03);}
 save(){return{done:this.done,wet:this.wet,strokes:this.done?[]:this.strokes};}
}
