import * as THREE from 'three';
import { RoomEnvironment } from 'three/addons/environments/RoomEnvironment.js';
import { makeWorld, ROOM_NAMES, BIN_INFO, roomAt } from './world.js';
import { TOOLS, makeToolView } from './tools.js';
import { DirtPatch } from './cleaning.js';
import { CONTRACTS,applyContract } from './contracts.js';
import { renderBudget,batchScenery } from './performance.js';
import { drawHouseMap } from './floorplan.js';
import { MOUSE_GAIN,LOCKED_MOUSE_SENSITIVITY,FREE_MOUSE_SENSITIVITY,edgeTurnSpeed } from './mouse-look.js';
import { sortingResult, movePlayer, PREPARATION } from './rules.js';
import { makeRinseAnimation } from './rinsing.js';

const $=id=>document.getElementById(id), STORE='home-care-3d-v1';
let resetting=false;
const state={items:{},patches:{},vents:{},hazards:{},generated:[],time:0,mistakes:0,finished:false,reflection:'',sound:true,quality:'auto',qualityVersion:2,inputMode:'auto',hints:true,contract:{id:'weekend',seed:1}};
try{const s=JSON.parse(localStorage.getItem(STORE));if(s&&typeof s==='object'){Object.assign(state,s);if(s.qualityVersion!==2)state.quality='auto';}}catch{}
state.qualityVersion=2;
if(!['auto','low','high'].includes(state.quality))state.quality='auto';
state.contract||={id:'weekend',seed:1};state.inputMode||='auto';if(state.hints===undefined)state.hints=true;
const contract=CONTRACTS.find(c=>c.id===state.contract.id)||CONTRACTS[0];
let profile={total:0,counts:{}};try{Object.assign(profile,JSON.parse(localStorage.getItem(STORE+'-profile'))||{});}catch{}
THREE.Cache.enabled=true;
let adaptive=1,config=renderBudget(state.quality,innerWidth,innerHeight,devicePixelRatio),detailed=null,detailedModule=null,detailedEnv=null,qualityTicket=0;
const metrics={fps:0,frameMs:0,calls:0,triangles:0},canvas=$('view'), manager=new THREE.LoadingManager();let loaded=false,failedAssets=0;
manager.onError=url=>{failedAssets++;console.warn('Texture unavailable',url);};
manager.onLoad=()=>{loaded=true;needsRender=true;$('start-button').disabled=false;$('start-button').textContent=state.time>1?'이어서 청소하기':'집에 들어가기';};
let renderer;
try{renderer=new THREE.WebGLRenderer({canvas,antialias:false,powerPreference:'high-performance'});}catch(e){$('fatal-error').hidden=false;$('fatal-text').textContent='WebGL 2를 지원하는 Chrome 또는 Edge에서 열어 주세요. 브라우저 설정에서 그래픽 가속을 켠 뒤 다시 열 수 있어요.';throw e;}
renderer.setPixelRatio(config.ratio);renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=false;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.05;renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.autoClear=false;renderer.info.autoReset=false;
const scene=new THREE.Scene();scene.background=new THREE.Color('#c6d8d3');scene.fog=new THREE.Fog('#c6d8d3',24,70);
const camera=new THREE.PerspectiveCamera(67,innerWidth/innerHeight,.05,80);camera.rotation.order='YXZ';
const pmrem=new THREE.PMREMGenerator(renderer);const envScene=new RoomEnvironment();scene.environment=pmrem.fromScene(envScene,.04).texture;scene.environmentIntensity=.31;const baseEnvironment=scene.environment;envScene.dispose();pmrem.dispose();
scene.add(new THREE.HemisphereLight('#e6eee5','#747363',1.65));
const sun=new THREE.DirectionalLight('#fff0d0',3.8);sun.position.set(-5,5,-10);sun.target.position.set(-1,0,1);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-11,right:11,top:10,bottom:-10,near:.1,far:32});sun.shadow.bias=-.0002;sun.shadow.normalBias=.025;sun.shadow.radius=3;scene.add(sun,sun.target);
for(const [x,y,z,power]of[[-2.3,2.85,-1.4,18],[4,2.8,-1.6,15],[3.8,2.8,4.1,23],[-2,2.8,4.5,20]]){const l=new THREE.PointLight('#ffefd2',power,8,2);l.position.set(x,y,z);scene.add(l);}
const world=makeWorld(scene,manager,{lite:state.quality!=='high'});applyContract(world,state.contract);
const patches=world.decals.map(spec=>new DirtPatch(spec,scene,state.patches[spec.id]));
const view=makeToolView(renderer);view.scene.environment=scene.environment;
let garden=null;new THREE.TextureLoader(manager).load('./assets/textures/lite/garden.jpg',texture=>{garden=texture;texture.colorSpace=THREE.SRGBColorSpace;texture.mapping=THREE.EquirectangularReflectionMapping;if(state.quality!=='high'){scene.background=texture;scene.backgroundBlurriness=0;}});
const batching=batchScenery(scene);
const rinsing=makeRinseAnimation(scene),glassHazard=world.interactives.find(a=>a.id==='hazard-glass'),hazardPoint=new THREE.Vector3();
world.items.forEach(it=>{const saved=state.items[it.id];if(saved)Object.assign(it,saved);if(it.dropPosition)it.object.position.set(...it.dropPosition);if(it.done)it.object.visible=false;refreshItemAppearance(it);});
world.interactives.filter(x=>x.type==='hazard').forEach(it=>{if(state.hazards[it.id]){it.done=true;it.object.visible=false;}});
world.windows.forEach(it=>{if(state.vents[it.room]){it.done=true;if(it.pivot)it.pivot.rotation.y=.47;}});
world.interactives.filter(x=>x.type==='vent'&&!x.pivot).forEach(it=>it.done=!!state.vents[it.room]);
let yaw=state.yaw??.62,pitch=state.pitch??-.08,player=new THREE.Vector3(state.position?.x??-.4,1.62,state.position?.z??.66),room=roomAt(player.x,player.z);
let running=false,started=false,tool='hand',holding=null,target=null,cleaning=false,pointerLocked=false,lastFrame=performance.now(),time=0,lastMeasure=0,lastSave=0,lastFoot=0,lastHint='',lastHintAt=0,mouseMoved=false,keyboardLook=false,lastCleaningTool='vacuum',lastRay=0,lastHUD=0,lastPresented=0,frameCount=0,fpsStamp=performance.now(),slowFrames=0,touchMode=false,needsRender=true;
const keys=new Set(),keyFrames=new Map(),ray=new THREE.Raycaster(),cursor=new THREE.Vector2(),touchMove={x:0,y:0},touchLook={id:null,x:0,y:0};
let interactBusy=false,moving=0,toastTimer,bannerTimer,pauseReturn='',mouseOrigin=null,lockPending=false,edgeTurn=0,edgeDirection=0,rayObjects=null,rayObjectCount=0,pendingContract=null;ray.far=3.05;
const recentRooms=new Set();
const outline=new THREE.Box3Helper(new THREE.Box3(),0xf4d897);outline.material.transparent=true;outline.material.opacity=.65;outline.material.depthTest=true;outline.visible=false;scene.add(outline);

// A bounded particle pool makes the work visible without allocating per frame.
const particleCount=160,particlePositions=new Float32Array(particleCount*3),particleLife=new Float32Array(particleCount),particleVelocity=Array.from({length:particleCount},()=>new THREE.Vector3());
particlePositions.fill(1000);const pgeo=new THREE.BufferGeometry();pgeo.setAttribute('position',new THREE.BufferAttribute(particlePositions,3));const pmaterial=new THREE.PointsMaterial({color:'#e1d8b8',size:.028,transparent:true,opacity:.8,depthWrite:false});const particles=new THREE.Points(pgeo,pmaterial);particles.frustumCulled=false;scene.add(particles);let particleIndex=0;
function emitParticles(hit,type){for(let n=0;n<3;n++){let i=particleIndex++%particleCount;particleLife[i]=.25+Math.random()*.22;let v=particleVelocity[i],p=hit.clone();if(type==='spray'){const origin=player.clone().add(new THREE.Vector3(.24,-.23,-.54).applyEuler(camera.rotation));p.copy(origin);v.copy(hit).sub(origin).multiplyScalar(4.2);}else{p.x+=(Math.random()-.5)*.14;p.z+=(Math.random()-.5)*.14;p.y+=.02;v.set((Math.random()-.5)*.28,.3+Math.random()*.5,(Math.random()-.5)*.28);}particlePositions[i*3]=p.x;particlePositions[i*3+1]=p.y;particlePositions[i*3+2]=p.z;pmaterial.color.set(type==='spray'?'#d2f2f2':type==='vacuum'?'#bbab89':'#e7e6cb');}}

// Short procedural sounds, started only after the player's first gesture.
let audioCtx,gain,noise;
function initAudio(){try{if(!audioCtx){audioCtx=new (window.AudioContext||window.webkitAudioContext)();gain=audioCtx.createGain();gain.gain.value=0;gain.connect(audioCtx.destination);const b=audioCtx.createBuffer(1,audioCtx.sampleRate*2,audioCtx.sampleRate),d=b.getChannelData(0);for(let i=0;i<d.length;i++)d[i]=(Math.random()*2-1)*.6;noise=audioCtx.createBufferSource();noise.buffer=b;noise.loop=true;const filter=audioCtx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=650;noise.connect(filter);filter.connect(gain);noise.start();}if(audioCtx.state==='suspended')audioCtx.resume();}catch{}}
function ping(freq=650){if(!audioCtx||!state.sound)return;const osc=audioCtx.createOscillator(),g=audioCtx.createGain();osc.type='sine';osc.frequency.setValueAtTime(freq,audioCtx.currentTime);osc.frequency.exponentialRampToValueAtTime(freq*1.5,audioCtx.currentTime+.13);g.gain.setValueAtTime(.035,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+.22);osc.connect(g);g.connect(audioCtx.destination);osc.start();osc.stop(audioCtx.currentTime+.25);}
function inputHint(text){if(!touchMode)return text;return text.replaceAll('클릭 누르기 / Space','‘청소’ 누르기').replaceAll('클릭 누르기','‘청소’ 누르기').replaceAll('E 집기 / 놓기','‘집기·사용’ 버튼').replaceAll('E ·','집기·사용 ·').replaceAll('바라보고 E','바라보고 ‘집기·사용’').replaceAll('E를 눌러요','‘집기·사용’을 눌러요').replaceAll('싱크대에서 E','싱크대에서 ‘집기·사용’').replaceAll('R 키로','분리 버튼으로').replaceAll('R로','분리 버튼으로');}
function toast(text,ms=3600){text=inputHint(text);if(lastHint===text&&performance.now()-lastHintAt<1800)return;lastHint=text;lastHintAt=performance.now();$('toast').textContent=text;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),ms);}
function save(){if(resetting)return;try{for(const it of world.items)state.items[it.id]={done:it.done,prepared:it.prepared,labelRemoved:it.labelRemoved,dropPosition:it.dropPosition};for(const p of patches)state.patches[p.id]=p.save();state.position={x:player.x,z:player.z};state.yaw=yaw;state.pitch=pitch;state.holdingId=holding?.id||null;state.reflection=$('reflection').value;localStorage.setItem(STORE,JSON.stringify(state));}catch{toast('이 브라우저에서는 자동 저장을 사용할 수 없어요.',2500);}}
function stats(forRoom){const its=world.items.filter(x=>x.room===forRoom),ps=patches.filter(x=>x.room===forRoom),hs=world.interactives.filter(x=>x.type==='hazard'&&x.room===forRoom),vent=forRoom!=='hall';const done=its.filter(x=>x.done).length+ps.reduce((n,p)=>n+p.progress,0)+hs.filter(x=>x.done).length+(state.vents[forRoom]?1:0),total=its.length+ps.length+hs.length+(vent?1:0);return {items:its,patches:ps,hazards:hs,done,total,percent:total?Math.min(100,Math.round(done/total*100)):100,complete:its.every(x=>x.done)&&ps.every(x=>x.done)&&hs.every(x=>x.done)&&(!vent||state.vents[forRoom])};}
function updateHUD(){room=roomAt(player.x,player.z);const s=stats(room);$('room-name').textContent=ROOM_NAMES[room];$('room-count').textContent=room==='hall'?'분리배출':`${s.percent}%`;$('room-bar').style.width=room==='hall'?'100%':`${s.percent}%`;
 if(room==='hall'){$('objective').textContent=holding?'들고 온 물건을 알맞은 함에 분리배출하기':'비우고, 헹구고, 분리하고, 섞지 않기';$('checklist').innerHTML='<div class="list-title">분리배출 순서</div><p>내용물 비우기</p><p>깨끗이 헹구기</p><p>다른 재질 분리하기</p><p>종류별로 따로 모으기</p>';}
 else{const sorted=s.items.filter(x=>x.done).length,dry=s.patches.filter(x=>x.kind==='dust'),wet=s.patches.filter(x=>x.kind!=='dust');let objective=!state.vents[room]?'먼저 환기하고, 위험한 물건 확인하기':s.hazards.some(x=>!x.done)?'깨진 유리를 발견했어요. 어른에게 도움 요청하기':sorted<s.items.length?'물건은 제자리로, 쓰레기는 분리배출대로':dry.some(x=>!x.done)?'높은 곳부터, 마른 먼지 먼저 치우기':wet.some(x=>!x.done)?'얼룩을 물로 불린 뒤 알맞게 닦기':'이 공간을 쾌적하게 돌봤어요';$('objective').textContent=objective;
  const row=(done,text,count='')=>`<p class="${done?'done':''}">${text}<b>${count}</b></p>`;$('checklist').innerHTML='<div class="list-title">이 공간의 할 일</div>'+row(!!state.vents[room],'환기하기')+(s.hazards.length?row(s.hazards.every(x=>x.done),'위험한 물건 알리기'):'')+row(sorted===s.items.length,'물건 정리 · 분리배출',`${sorted}/${s.items.length}`)+row(dry.every(x=>x.done),'마른 먼지 제거',`${dry.filter(x=>x.done).length}/${dry.length}`)+row(wet.every(x=>x.done),'얼룩 닦기',`${wet.filter(x=>x.done).length}/${wet.length}`);
 }
 for(const id of['bedroom','kitchen','bathroom']){const r=stats(id);document.querySelector(`[data-room="${id}"] span`).textContent=`${r.percent}% 완료
정리 ${r.items.filter(x=>x.done).length}/${r.items.length} · 청소 ${r.patches.filter(x=>x.done).length}/${r.patches.length}`;if(r.complete&&!recentRooms.has(id)){recentRooms.add(id);if(started){$('room-banner').hidden=false;$('room-banner').textContent=`✓ ${ROOM_NAMES[id]}, 쾌적하게 완료`;clearTimeout(bannerTimer);bannerTimer=setTimeout(()=>$('room-banner').hidden=true,4000);ping(760);}}}
 
 if(['bedroom','kitchen','bathroom'].every(id=>stats(id).complete)&&world.items.every(item=>item.done)&&!state.finished){state.finished=true;recordCompletion();save();setTimeout(showFinish,1200);}
}
function refreshItemAppearance(item){item.object.traverse(o=>{if(item.labelRemoved&&['label','pump'].includes(o.userData.part))o.visible=false;if(item.prepared&&o.userData.part==='contents')o.visible=false;});}
function updateHeld(){const panel=$('held');panel.hidden=!holding;document.body.classList.toggle('has-held',!!holding);if(!holding){view.setCarried(null);return;}refreshItemAppearance(holding);view.setCarried(holding.object);$('held-name').textContent=holding.prepared?holding.name.replace('음료가 남은','깨끗한').replace('우유가 남은','깨끗한'):holding.name;let steps=[];if(holding.storage)steps.push('✓ 다시 쓸 물건 · 제자리에 보관');else{if(holding.prep)steps.push(`${holding.prepared?'✓':'○'} 비우고 헹구기${holding.bin==='carton'?' · 펼쳐 말리기':''}`);if(holding.peel)steps.push(`${holding.labelRemoved?'✓':'○'} ${holding.id==='plastic'?'펌프와 라벨':'비닐 라벨'} 분리`);steps.push('○ 현관에서 종류별 분리배출');}$('held-steps').innerHTML=steps.join('<br>');$('peel-button').hidden=!holding.peel||holding.labelRemoved;$('held-tip').textContent=holding.storage?'보관 장소를 바라보고 E':holding.prep&&!holding.prepared?'주방 싱크대에서 E':holding.peel&&!holding.labelRemoved?'R 키로 다른 재질 분리':'현관 분리수거함을 바라보고 E';$('held-tip').textContent=inputHint($('held-tip').textContent);}
function dropHolding(quiet=false){if(!holding)return true;if(interactBusy){toast('헹구기가 끝나면 도구를 바꿀 수 있어요.');return false;}const object=holding;object.dropPosition=[player.x,.032,player.z];object.object.position.set(...object.dropPosition);object.object.visible=true;object.object.updateMatrixWorld(true);holding=null;updateHeld();save();if(!quiet)toast('발밑에 내려놓았어요. 나중에 다시 주워 정리할 수 있어요.');return true;}
function setTool(id){if(!TOOLS.some(t=>t.id===id))return;if(holding&&id!=='hand'){if(!dropHolding(true))return;toast('물건을 발밑에 내려놓고 청소를 이어가요.');}tool=id;if(id!=='hand')lastCleaningTool=id;cleaning=false;view.set(id);const def=TOOLS.find(x=>x.id===id);$('tool-name').textContent=def.full;$('tool-hint').textContent=inputHint(def.hint);document.querySelectorAll('#toolbelt button').forEach(b=>{b.classList.toggle('selected',b.dataset.tool===id);b.setAttribute('aria-pressed',b.dataset.tool===id);});}
function resumeCleaning(){if(holding)setTool(lastCleaningTool);return !holding&&tool!=='hand';}
TOOLS.forEach((t,i)=>{const button=document.createElement('button');button.dataset.tool=t.id;button.setAttribute('aria-label',`${i+1} ${t.full}`);button.innerHTML=`<span class="key">${i+1}</span><svg viewBox="0 0 42 42" aria-hidden="true"><path d="${t.icon}"/></svg><span class="label">${t.name}</span>`;button.addEventListener('click',()=>{setTool(t.id);canvas.focus({preventScroll:true});});$('toolbelt').append(button);});setTool('hand');

function spawnSeparated(spec,restore=false){const group=new THREE.Group();group.position.set(spec.x,.027,spec.z);scene.add(group);if(spec.bin==='vinyl'){const mat=new THREE.MeshStandardMaterial({color:'#ccc4a3',roughness:.5,side:THREE.DoubleSide});const mesh=new THREE.Mesh(new THREE.PlaneGeometry(.22,.14),mat);mesh.rotation.set(-Math.PI/2,0,.2);mesh.position.y=.015;group.add(mesh);world.solid.push(mesh);}else{const mat=world.m.black;const o=world.box(.12,.025,.04,mat,0,.025,0,.007,group);world.cyl(.017,.017,.07,mat,-.025,.045,0,group);}
 const it={id:spec.id,name:spec.name,bin:spec.bin,room:spec.room,type:'item',object:group,done:false,prepared:true};if(state.items[it.id])Object.assign(it,state.items[it.id]);if(it.dropPosition)group.position.set(...it.dropPosition);if(it.done)group.visible=false;group.traverse(o=>{if(o.isMesh){o.userData.action=it;world.targets.push(o);}});world.interactives.push(it);world.items.push(it);if(!restore)state.generated.push(spec);return it;}
for(const spec of state.generated)spawnSeparated(spec,true);
function peel(){if(!running||!holding||interactBusy)return;if(!holding.peel){toast('이 물건에는 분리할 라벨이나 펌프가 없어요.');return;}if(holding.labelRemoved){toast('이미 다른 재질을 분리했어요.');return;}holding.labelRemoved=true;const front=new THREE.Vector3(-Math.sin(yaw),0,-Math.cos(yaw));const base=player.clone();const kind=holding.id==='plastic'?'샴푸통':'페트병';spawnSeparated({id:`${holding.id}-label`,name:`${kind}에서 떼어 낸 비닐 라벨`,bin:'vinyl',room,x:base.x,z:base.z});if(holding.id==='plastic')spawnSeparated({id:'plastic-pump',name:'금속 스프링이 든 샴푸 펌프',bin:'general',room,x:base.x+.06,z:base.z+.06});toast(holding.id==='plastic'?'펌프와 라벨을 분리했어요. 바닥에 둔 라벨은 비닐류, 복합재질 펌프는 일반 쓰레기로 처리해요.':'비닐 라벨을 분리했어요. 바닥에 둔 라벨도 비닐 수거함으로 가져가 주세요.',5000);updateHeld();updateHUD();save();ping(540);}
function actionAtCenter(){camera.position.copy(player);camera.rotation.set(pitch,yaw,0,'YXZ');camera.updateMatrixWorld();ray.setFromCamera(cursor,camera);const count=world.solid.length+world.targets.length;if(!rayObjects||rayObjectCount!==count){rayObjects=[...new Set([...world.solid,...world.targets,...patches.map(p=>p.mesh)])];rayObjectCount=count;}const hits=ray.intersectObjects(rayObjects,false);for(const h of hits){if(h.distance>3.05)return null;let o=h.object;let visible=true;while(o){if(!o.visible){visible=false;break;}o=o.parent;}if(!visible||h.object===outline)continue;const act=h.object.userData.action;if(act?.done&&(act.type==='item'||act.type==='hazard'))continue;if(h.object.material?.transparent&&h.object.material.opacity<.3&&!act&&!h.object.userData.patch)continue;if(act||h.object.userData.patch)return{...h,action:act,patch:h.object.userData.patch};return null;}return null;}
function updateTarget(){target=actionAtCenter();outline.visible=false;let title='',hint='',progress=0;
 if(interactBusy){$('target-title').textContent=rinsing.phase;$('target-hint').textContent='용기를 기울여 비우고 깨끗한 물로 헹궈요';$('work-ring').style.strokeDashoffset=132-rinsing.progress*132;return;}
 if(target?.patch){const p=target.patch;title=p.name;progress=p.progress;if(tool==='hand')hint='오른쪽에서 알맞은 청소 도구를 골라요';else if(p.kind!=='dust'&&tool==='spray')hint=`클릭 누르기 · 물로 불리기 ${Math.round(p.wet*100)}%`;else if(tool===p.tool)hint=p.kind!=='dust'&&p.wet<.65?'먼저 분무기로 얼룩을 불려요':`${Math.round(p.progress*100)}% 깨끗해졌어요${p.progress>=.8?' · 계속 닦으면 마무리 보정':' · 노란 부분을 닦아요'}`;else hint=p.kind==='dust'?(p.tool==='duster'?'높은 곳의 먼지 → 먼지떨이':'마른 먼지 → 청소기'):'물로 불린 뒤 표면에 맞게 닦아요';}
 else if(target?.action){const a=target.action;title=a.name;if(a.type==='item')hint=holding?'들고 있는 물건부터 정리해 주세요':'E · 손으로 집기';if(a.type==='storage')hint=holding?'E · 제자리에 정리하기':'물건의 제자리';if(a.type==='bin')hint=holding?'E · 분리배출하기':'가져온 쓰레기를 여기서 분리해요';if(a.type==='sink')hint=holding?.prep&&!holding.prepared?'E · 비우고 헹구기':'쓰레기의 내용물을 비우고 헹구는 곳';if(a.type==='vent')hint=a.done?'환기 중':`E · ${a.room==='bathroom'?'환풍기 켜기':'창문 열기'}`;if(a.type==='hazard')hint='E · 만지지 말고 어른에게 도움 요청';if(['item','hazard'].includes(a.type)){outline.box.setFromObject(a.object);outline.box.expandByScalar(.025);outline.visible=true;}}
 $('target-title').textContent=title;$('target-hint').textContent=inputHint(hint);$('reticle').classList.toggle('active',!!target);$('work-ring').style.strokeDashoffset=132-progress*132;
}
function dropInto(destination){const object=holding;if(object.storage){if(destination.type!=='storage'||destination.id!==object.storage){toast('물건의 쓰임을 생각해 알맞은 보관 장소에 놓아 주세요.');state.mistakes++;return;}object.done=true;holding=null;updateHeld();toast(`${object.name}, 제자리로 정리했어요.`);ping();save();updateHUD();return;}
 if(destination.type!=='bin'){toast('쓰레기는 현관의 분리배출대로 가져가 주세요.');return;}const result=sortingResult(object,destination.id);if(!result.ok){toast(result.reason,4200);state.mistakes++;return;}object.done=true;holding=null;updateHeld();toast(`${destination.name}에 올바르게 분리했어요. ${result.reason}`,4200);ping();save();updateHUD();}
function lookAtSink(){const dx=4.15-player.x,dz=-4.35-player.z;yaw=Math.atan2(-dx,-dz);pitch=Math.atan2(1.18-player.y,Math.hypot(dx,dz));mouseOrigin=null;showEdgeTurn(0);}
function reportHazard(a){a.done=true;a.object.visible=false;state.hazards[a.id]=true;$('hazard-marker').hidden=true;toast('어른에게 알렸어요. 어른이 깨진 유리를 안전하게 감싸 표시한 뒤, 지역의 배출 방법에 따라 처리했어요.',6000);ping(450);save();updateHUD();}
function updateHazardGuide(){const marker=$('hazard-marker');marker.hidden=!running||interactBusy||room!=='kitchen'||glassHazard.done;if(marker.hidden)return;
 const position=glassHazard.object.position,distance=Math.hypot(position.x-player.x,position.z-player.z);glassHazard.ring.scale.setScalar(1+Math.sin(time*3)*.045);
 hazardPoint.copy(position);hazardPoint.y=.35;hazardPoint.project(camera);
 const behind=hazardPoint.z>1,x=(hazardPoint.x*.5+.5)*innerWidth,y=(-hazardPoint.y*.5+.5)*innerHeight;
 const left=innerWidth>800?330:125,right=innerWidth-235;
 marker.style.left=`${Math.max(left,Math.min(right,behind?innerWidth*.55:x))}px`;marker.style.top=`${Math.max(100,Math.min(innerHeight-200,behind?innerHeight*.58:y-55))}px`;
 $('hazard-distance').textContent=`${distance.toFixed(1)} m · ${distance<=2.8?'눌러서 어른에게 알리기':'눌러서 위치 보기'}`;
}
$('hazard-marker').onclick=()=>{if(!running||glassHazard.done||interactBusy)return;const p=glassHazard.object.position,dx=p.x-player.x,dz=p.z-player.z;if(Math.hypot(dx,dz)<=2.8){reportHazard(glassHazard);return;}yaw=Math.atan2(-dx,-dz);pitch=Math.atan2(.15-player.y,Math.hypot(dx,dz));mouseOrigin=null;toast('주황색 원으로 표시된 유리 쪽으로 가까이 가세요. 맨손으로 줍지 않아요.');};
function interact(){if(!running||interactBusy)return;target=actionAtCenter();const a=target?.action;if(!a){toast(holding?'알맞은 보관 장소나 분리수거함을 가까이에서 바라보세요.':'물건이나 창문을 가까이에서 바라보고 E를 눌러요.');return;}
 if(a.type==='vent'){if(a.done){toast('이미 환기하고 있어요.');return;}a.done=true;state.vents[a.room]=true;toast(a.room==='bathroom'?'환풍기를 켰어요. 습기가 빠져나가도록 환기해요.':'창문을 열었어요. 정리하고 청소하는 동안 환기해요.');ping(500);save();updateHUD();return;}
 if(a.type==='hazard'){reportHazard(a);return;}
 if(a.type==='item'){if(holding){toast('들고 있는 물건을 먼저 정리해 주세요.');return;}setTool('hand');holding=a;a.object.visible=false;updateHeld();toast(a.storage?'쓰임이 같은 물건끼리, 정해진 제자리에 놓아요.':PREPARATION[a.bin]||'현관 분리배출대의 알맞은 수거함까지 가져가세요.');return;}
 if(a.type==='sink'){if(!holding){toast('내용물이 남은 페트병·종이팩·캔·샴푸통을 들고 사용해요.');return;}if(!holding.prep||holding.prepared){toast('이미 비우고 헹군 물건이에요.');return;}interactBusy=true;cleaning=false;keys.clear();touchMove.x=touchMove.y=0;rinsing.start(holding);view.setCarried(null);lookAtSink();document.body.classList.add('rinsing');$('peel-button').disabled=$('drop-button').disabled=true;return;}
 if(a.type==='bin'||a.type==='storage'){if(!holding){toast(a.type==='bin'?'쓰레기를 손으로 집어서 가져와 주세요.':'물건을 손으로 집어서 가져와 주세요.');return;}dropInto(a);}
}
function doClean(dt){if(!target?.patch||target.patch.done||holding||tool==='hand')return false;const p=target.patch;if(!state.vents[p.room]){toast('먼저 창문이나 환풍기를 열어 환기해 주세요.');return false;}if(world.interactives.some(a=>a.type==='hazard'&&a.room===p.room&&!a.done)){toast('먼저 깨진 유리를 어른에게 알려 주세요. 위험한 물건을 안전하게 처리한 뒤 청소해요.');return false;}if(tool==='spray'){if(p.kind==='dust'){toast('마른 먼지에 물을 뿌리면 엉겨 붙어요. 먼저 마른 도구로 제거해요.');return false;}p.spray(dt);emitParticles(target.point,'spray');return true;}
 if(tool!==p.tool){if(tool==='hand')return false;toast(p.kind==='dust'?(p.tool==='duster'?'높은 곳의 먼지는 먼지떨이로 먼저 제거해요.':'마른 먼지와 부스러기는 청소기로 먼저 제거해요.'):p.tool==='mop'?'바닥 얼룩은 물로 불린 뒤 밀대로 닦아요.':'표면의 얼룩은 물로 불린 뒤 솔이나 수세미로 닦아요.');return false;}
 if(p.kind!=='dust'&&p.wet<.65){toast('마른 얼룩이에요. 분무기로 물을 충분히 뿌려 불린 뒤 닦아 주세요.');return false;}
 if(p.tool==='mop'&&patches.some(d=>d.room===p.room&&d.kind==='dust'&&!d.done)){toast('마른 먼지를 먼저 제거하면 바닥에 더러움이 번지지 않아요.');return false;}
 if(p.tool==='vacuum'&&patches.some(d=>d.room===p.room&&d.tool==='duster'&&!d.done)){toast('높은 곳에서 먼지가 떨어져요. 책상 위 먼지를 먼저 털어 주세요.');return false;}
 const radius=tool==='mop'?.3:tool==='vacuum'?.27:tool==='brush'?.18:.23;const before=p.done;p.clean(target.uv.x,target.uv.y,radius,Math.min(dt,.1));if(Math.random()>.6)emitParticles(target.point,tool);if(p.done&&!before){toast('깨끗해졌어요! 다음 노란 구역을 찾아보세요.');ping(850);save();updateHUD();}return true;
}

function showEdgeTurn(rate){edgeTurn=rate;const direction=Math.sign(rate);if(direction===edgeDirection)return;edgeDirection=direction;$('look-mode').hidden=!direction;$('look-mode').textContent=direction>0?'← 가장자리 회전':'가장자리 회전 →';}
function requestLock(){if(touchMode||pointerLocked||lockPending||!canvas.requestPointerLock)return;lockPending=true;mouseOrigin=null;showEdgeTurn(0);try{const promise=canvas.requestPointerLock();promise?.catch(()=>{lockPending=false;});}catch{lockPending=false;}}
function begin(){if(!loaded)return;started=true;running=true;needsRender=true;mouseOrigin=null;showEdgeTurn(0);for(const id of['start-screen','pause-screen','guide-screen','map-screen','finish-screen','contracts-screen'])$(id).hidden=true;$('hud').hidden=false;canvas.focus({preventScroll:true});initAudio();requestLock();updateHUD();if(state.time<1)toast(touchMode?'왼쪽으로 걷고 화면을 밀어 둘러보세요. 먼저 창문에서 집기·사용을 눌러요.':'마우스를 움직여 둘러보세요. 먼저 창문을 바라보고 E로 환기해요.',5000);}
function pause(id='pause-screen'){if(!started)return;running=false;cleaning=false;showEdgeTurn(0);keys.clear();touchMove.x=touchMove.y=0;touchLook.id=null;mouseOrigin=null;joystick.firstElementChild.style.transform='';$('touch-clean').classList.remove('pressed');document.exitPointerLock?.();if(gain)gain.gain.setTargetAtTime(0,audioCtx.currentTime,.05);for(const name of['pause-screen','guide-screen','map-screen','finish-screen','contracts-screen'])$(name).hidden=true;$(id).hidden=false;save();}
function closePanel(id){$(id).hidden=true;if(started)begin();else $('start-screen').hidden=false;}
function guide(){if(started)pause('guide-screen');else{$('start-screen').hidden=true;$('guide-screen').hidden=false;}}
function openMap(){pause('map-screen');updateHUD();drawHouseMap(renderer,scene,world,$('house-plan'),player,yaw);}
function recordCompletion(){if(state.recorded)return;state.recorded=true;profile.total++;profile.counts[contract.id]=(profile.counts[contract.id]||0)+1;try{localStorage.setItem(STORE+'-profile',JSON.stringify(profile));}catch{}}
function showFinish(){if(!state.finished)return;recordCompletion();pause('finish-screen');$('finish-stats').innerHTML=contract.name+' 완료<br>돌본 공간 <b>3곳</b><br>정리·분리배출 <b>'+world.items.length+'개</b><br>닦은 구역 <b>'+patches.length+'곳</b><br>지금까지 <b>'+profile.total+'회</b> 집을 돌봤어요.';}
function showContracts(){pause('contracts-screen');$('contract-confirm').hidden=true;$('contract-history').textContent='지금까지 '+profile.total+'회 완료 · 다시 시작하면 물건과 얼룩 배치가 달라져요.';$('contract-list').innerHTML=CONTRACTS.map(c=>'<button data-contract="'+c.id+'" style="--accent:'+c.accent+'"><strong>'+c.name+'</strong><span>'+c.description+'</span><small>'+(profile.counts[c.id]||0)+'회 완료</small></button>').join('');$('contract-list').querySelectorAll('button').forEach(button=>button.onclick=()=>{pendingContract=button.dataset.contract;$('contract-confirm-text').textContent=state.finished?'새 배치로 청소를 시작할까요?':'현재 진행을 마치지 않고 새 의뢰를 시작할까요?';$('contract-confirm').hidden=false;});}
function restartContract(next=false){const nextState={quality:state.quality,qualityVersion:2,inputMode:state.inputMode,sound:state.sound,hints:state.hints,contract:next?{id:pendingContract,seed:Date.now()>>>0}:state.contract};try{localStorage.setItem(STORE,JSON.stringify(nextState));}catch{toast('이 기기에서는 새 진행 기록을 저장할 수 없어요.');return;}resetting=true;location.reload();}
function applyInputMode(){touchMode=state.inputMode==='touch'||state.inputMode==='auto'&&(matchMedia('(pointer:coarse)').matches||navigator.maxTouchPoints>0);document.body.classList.toggle('touch',touchMode);mouseOrigin=null;showEdgeTurn(0);touchMove.x=touchMove.y=0;if(touchMode)document.exitPointerLock?.();$('tool-hint').textContent=inputHint(TOOLS.find(t=>t.id===tool).hint);if(holding)updateHeld();}
$('start-button').onclick=begin;$('resume-button').onclick=begin;$('pause-button').onclick=()=>pause();$('guide-button').onclick=guide;$('settings-guide').onclick=guide;$('map-button').onclick=openMap;$('hud-map').onclick=openMap;$('map-resume').onclick=begin;$('finish-explore').onclick=begin;
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closePanel(b.dataset.close));
$('restart-button').onclick=()=>$('restart-confirm').hidden=false;$('restart-no').onclick=()=>$('restart-confirm').hidden=true;$('restart-yes').onclick=()=>restartContract(false);
$('contracts-button').onclick=$('next-contract').onclick=showContracts;$('contract-no').onclick=()=>$('contract-confirm').hidden=true;$('contract-yes').onclick=()=>restartContract(true);
$('drop-button').onclick=()=>dropHolding();$('peel-button').onclick=peel;
$('hint-button').setAttribute('aria-pressed',state.hints);$('hint-button').onclick=()=>{state.hints=!state.hints;$('hint-button').setAttribute('aria-pressed',state.hints);save();};
$('sound').checked=state.sound;$('sound').onchange=e=>{state.sound=e.target.checked;save();};$('quality').value=state.quality;
$('input-mode').value=state.inputMode;$('input-mode').onchange=e=>{state.inputMode=e.target.value;applyInputMode();save();};applyInputMode();
async function quality(){const ticket=++qualityTicket;adaptive=1;config=renderBudget(state.quality,innerWidth,innerHeight,devicePixelRatio,adaptive);renderer.setPixelRatio(config.ratio);renderer.shadowMap.enabled=false;world.setDetail(false);if(detailed){detailed.dispose();detailed=null;}scene.environment=baseEnvironment;view.scene.environment=baseEnvironment;if(garden){scene.background=garden;scene.backgroundBlurriness=0;}resize();needsRender=true;
 if(config.detailed){try{detailedModule||=await import('./quality-high.js');if(ticket!==qualityTicket||state.quality!=='high')return;detailed=detailedModule.createDetailedRenderer(renderer,scene,camera);renderer.shadowMap.enabled=true;world.setDetail(true);resize();needsRender=true;detailedEnv||=await detailedModule.detailedEnvironment(renderer);if(ticket!==qualityTicket||state.quality!=='high')return;scene.background=detailedEnv.background;scene.backgroundBlurriness=.035;scene.environment=detailedEnv.environment;view.scene.environment=scene.environment;needsRender=true;}catch{toast('높은 화질을 사용할 수 없어 기본 화질로 계속해요.');}}
}
$('quality').onchange=e=>{state.quality=e.target.value;quality();save();};$('reflection').value=state.reflection||'';$('reflection').oninput=save;
$('contract-label').textContent=contract.name;$('start-contract').textContent=contract.name;
$('export-button').onclick=()=>{const text=`우리집 새로고침 · 나의 돌봄 기록\n\n2022 개정 실과 [6실02-10]\n완료한 공간: 나의 방, 주방, 욕실\n정리·분리배출: ${world.items.length}개\n닦은 구역: ${patches.length}곳\n\n익힌 방법\n- 환기하고 위험한 물건 확인하기\n- 물건을 제자리에 정리하기\n- 높은 곳부터, 마른 먼지를 먼저 제거하기\n- 얼룩을 불리고 알맞은 도구로 닦기\n- 비우고, 헹구고, 다른 재질을 분리해 종류별 배출하기\n\n집에서 실천할 한 가지\n${$('reflection').value||'아직 작성하지 않았어요.'}\n\n실제 배출 품목과 방법은 우리 지역 안내를 확인하세요.\n`;const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='우리집-3D-돌봄-기록.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
document.addEventListener('pointerlockchange',()=>{const wasLocked=pointerLocked;pointerLocked=document.pointerLockElement===canvas;lockPending=false;mouseOrigin=null;showEdgeTurn(0);if(pointerLocked&&(!running||touchMode)){document.exitPointerLock?.();return;}if(wasLocked&&!pointerLocked&&running)pause();});
document.addEventListener('pointerlockerror',()=>{pointerLocked=false;lockPending=false;});
document.addEventListener('mousemove',e=>{if(!running||touchMode||e.sourceCapabilities?.firesTouchEvents)return;if(pointerLocked){yaw-=e.movementX*LOCKED_MOUSE_SENSITIVITY;pitch-=e.movementY*LOCKED_MOUSE_SENSITIVITY;}else if(e.target===canvas){if(mouseOrigin){yaw-=(e.clientX-mouseOrigin.x)*FREE_MOUSE_SENSITIVITY;pitch-=(e.clientY-mouseOrigin.y)*FREE_MOUSE_SENSITIVITY;}mouseOrigin={x:e.clientX,y:e.clientY};}else{mouseOrigin=null;showEdgeTurn(0);}pitch=Math.max(-1.4,Math.min(1.35,pitch));});
canvas.addEventListener('pointerleave',()=>{mouseOrigin=null;showEdgeTurn(0);});
canvas.addEventListener('pointerdown',e=>{if(!running)return;if(e.pointerType==='touch'||e.pointerType==='pen'||touchMode){e.preventDefault();if(touchLook.id!==null)return;if(state.inputMode==='auto'){touchMode=true;document.body.classList.add('touch');}touchLook.id=e.pointerId;touchLook.x=e.clientX;touchLook.y=e.clientY;canvas.setPointerCapture(e.pointerId);}else if(e.button===0){canvas.focus({preventScroll:true});requestLock();if(resumeCleaning())cleaning=true;}});
canvas.addEventListener('pointermove',e=>{if(e.pointerId!==touchLook.id||!running)return;yaw-=(e.clientX-touchLook.x)*.004;pitch=Math.max(-1.4,Math.min(1.35,pitch-(e.clientY-touchLook.y)*.004));touchLook.x=e.clientX;touchLook.y=e.clientY;});
const releaseLook=e=>{if(e.pointerId===touchLook.id)touchLook.id=null;if(e.pointerType==='mouse'&&!touchMode)cleaning=false;};
canvas.addEventListener('pointerup',releaseLook);canvas.addEventListener('pointercancel',releaseLook);canvas.addEventListener('lostpointercapture',releaseLook);document.addEventListener('mouseup',()=>{if(!touchMode)cleaning=false;});
let wheelTotal=0,lastWheel=0;document.addEventListener('wheel',e=>{if(!running||touchMode||e.ctrlKey||e.metaKey)return;e.preventDefault();wheelTotal+=e.deltaY;if(Math.abs(wheelTotal)<25||performance.now()-lastWheel<110)return;const index=TOOLS.findIndex(t=>t.id===tool),direction=Math.sign(wheelTotal);setTool(TOOLS[(index+direction+TOOLS.length)%TOOLS.length].id);wheelTotal=0;lastWheel=performance.now();},{passive:false});
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA','SELECT'].includes(e.target.tagName))return;if(running&&['Space','ArrowUp','ArrowDown','ArrowLeft','ArrowRight'].includes(e.code))e.preventDefault();if(e.code==='Escape'){if(started){if(running)pause();else begin();}return;}if(e.code==='KeyM'&&started&&!e.repeat){if($('map-screen').hidden)openMap();else begin();return;}if(!running)return;keys.add(e.code);if(!e.repeat)keyFrames.set(e.code,time);if(e.code==='KeyE'&&!e.repeat)interact();if(e.code==='KeyR'&&!e.repeat)peel();if(e.code==='KeyQ'&&!e.repeat)dropHolding();if(e.code==='KeyH'&&!e.repeat)$('hint-button').click();if(e.code.startsWith('Digit')){const n=Number(e.code.slice(5));if(n>=1&&n<=TOOLS.length)setTool(TOOLS[n-1].id);}if(e.code==='Space'&&resumeCleaning())cleaning=true;});
document.addEventListener('keyup',e=>{if(running&&time-(keyFrames.get(e.code)??-10)<.05){let f=e.code==='KeyW'?1:e.code==='KeyS'?-1:0,d=e.code==='KeyD'?1:e.code==='KeyA'?-1:0;if(f||d)movePlayer(player,(d*Math.cos(yaw)-f*Math.sin(yaw))*.095,(-d*Math.sin(yaw)-f*Math.cos(yaw))*.095,world.colliders);if(e.code==='ArrowLeft')yaw+=.035;if(e.code==='ArrowRight')yaw-=.035;if(e.code==='ArrowUp')pitch=Math.min(1.35,pitch+.035);if(e.code==='ArrowDown')pitch=Math.max(-1.4,pitch-.035);if(e.code==='Space'){target=actionAtCenter();doClean(.09);}}keys.delete(e.code);keyFrames.delete(e.code);if(e.code==='Space')cleaning=false;});
window.addEventListener('blur',()=>{keys.clear();cleaning=false;if(running)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&running)pause();needsRender=true;});window.addEventListener('pagehide',save);
const joystick=$('joystick');let joyId=null;
function joy(e){const rect=joystick.getBoundingClientRect();touchMove.x=Math.max(-1,Math.min(1,(e.clientX-rect.left-rect.width/2)/36));touchMove.y=Math.max(-1,Math.min(1,(e.clientY-rect.top-rect.height/2)/36));joystick.firstElementChild.style.transform='translate('+(touchMove.x*25)+'px,'+(touchMove.y*25)+'px)';}
joystick.onpointerdown=e=>{if(!running)return;e.preventDefault();joyId=e.pointerId;joystick.setPointerCapture(e.pointerId);joy(e);};joystick.onpointermove=e=>{if(joyId===e.pointerId)joy(e);};joystick.onpointerup=joystick.onpointercancel=joystick.onlostpointercapture=()=>{joyId=null;touchMove.x=touchMove.y=0;joystick.firstElementChild.style.transform='';};
let cleanTouchStart=0;$('touch-clean').onpointerdown=e=>{e.preventDefault();if(!running||!resumeCleaning())return;$('touch-clean').setPointerCapture(e.pointerId);cleaning=true;cleanTouchStart=performance.now();$('touch-clean').classList.add('pressed');};
$('touch-clean').onpointerup=$('touch-clean').onpointercancel=()=>{if(cleaning&&performance.now()-cleanTouchStart<90){target=actionAtCenter();doClean(.09);}cleaning=false;$('touch-clean').classList.remove('pressed');};$('touch-clean').onlostpointercapture=()=>{cleaning=false;$('touch-clean').classList.remove('pressed');};$('touch-interact').onclick=interact;
function resize(){mouseOrigin=null;showEdgeTurn(0);config=renderBudget(state.quality,innerWidth,innerHeight,devicePixelRatio,adaptive);renderer.setPixelRatio(config.ratio);renderer.setSize(innerWidth,innerHeight);detailed?.resize(Math.round(innerWidth*config.ratio),Math.round(innerHeight*config.ratio));camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();view.resize(innerWidth,innerHeight);needsRender=true;}window.addEventListener('resize',resize);resize();quality();
function frame(now){requestAnimationFrame(frame);if(document.hidden||!loaded)return;const interval=running?1000/config.fps:200;if(now-lastPresented<interval-.7)return;if(started&&!running&&!needsRender)return;const cpuStart=performance.now(),elapsed=now-lastFrame,dt=Math.min(elapsed/1000,.07);lastFrame=now;lastPresented=now;time+=dt;let activeWork=false;
 if(running){showEdgeTurn(edgeTurnSpeed(mouseOrigin,innerWidth,!touchMode&&!pointerLocked));yaw+=edgeTurn*dt;state.time+=dt;let forward=(keys.has('KeyW')?1:0)-(keys.has('KeyS')?1:0)-touchMove.y,side=(keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0)+touchMove.x;if(interactBusy)forward=side=0;const mag=Math.hypot(forward,side);if(mag>1){forward/=mag;side/=mag;}moving=Math.min(1,mag);movePlayer(player,(side*Math.cos(yaw)-forward*Math.sin(yaw))*dt*2.35,(-side*Math.sin(yaw)-forward*Math.cos(yaw))*dt*2.35,world.colliders);if(keys.has('ArrowLeft'))yaw+=dt*1.22;if(keys.has('ArrowRight'))yaw-=dt*1.22;if(keys.has('ArrowUp'))pitch+=dt*.92;if(keys.has('ArrowDown'))pitch-=dt*.92;pitch=Math.max(-1.4,Math.min(1.35,pitch));if(interactBusy)lookAtSink();camera.position.copy(player);camera.position.y+=Math.sin(time*13)*.006*moving;camera.rotation.set(pitch,yaw,0,'YXZ');camera.updateMatrixWorld();if(time-lastRay>.055){lastRay=time;updateTarget();}if(interactBusy){const finished=rinsing.update(dt);if(finished){finished.prepared=true;interactBusy=false;document.body.classList.remove('rinsing');$('peel-button').disabled=$('drop-button').disabled=false;updateHeld();save();ping(570);toast(finished.bin==='carton'?'비우고 헹군 종이팩을 펼쳐 말렸어요. 종이팩 수거함으로 가져가요.':'내용물을 비우고 헹궜어요. 다른 재질이 붙어 있다면 R로 분리해요.');}}if(cleaning&&!interactBusy)activeWork=doClean(dt);if(time-lastSave>8){lastSave=time;save();}if(time-lastHUD>.45){lastHUD=time;updateHUD();}
  if(state.quality==='auto'){slowFrames=elapsed>45?slowFrames+1:Math.max(0,slowFrames-1);if(slowFrames>55&&adaptive>.65){adaptive=Math.max(.65,adaptive-.1);resize();slowFrames=0;}}
 }else{moving=0;if(!started){camera.position.set(-.4,1.62,.66);camera.rotation.set(-.065,.65,0,'YXZ');}}
 updateHazardGuide();
 for(const p of patches){const relevant=state.hints&&running&&p.room===room&&!p.done&&(tool==='hand'||tool===p.tool||tool==='spray'&&p.kind!=='dust');p.showGuide(relevant,target?.patch===p,time);}
 for(const w of world.windows)if(w.pivot&&w.done)w.pivot.rotation.y=THREE.MathUtils.damp(w.pivot.rotation.y,.47,3,dt);
 let particleChanged=false;for(let i=0;i<particleCount;i++){if(particleLife[i]>0){particleChanged=true;particleLife[i]-=dt;particlePositions[i*3]+=particleVelocity[i].x*dt;particlePositions[i*3+1]+=particleVelocity[i].y*dt;particlePositions[i*3+2]+=particleVelocity[i].z*dt;if(particleLife[i]<=0)particlePositions[i*3+1]=1000;}}if(particleChanged)pgeo.attributes.position.needsUpdate=true;
 if(gain)gain.gain.setTargetAtTime(running&&activeWork&&state.sound?(tool==='vacuum'?.065:.018):0,audioCtx.currentTime,.08);
 view.update(dt,time,moving,activeWork,room);renderer.info.reset();renderer.clear();if(detailed&&config.detailed)detailed.render(dt);else renderer.render(scene,camera);if(started&&!interactBusy)view.render();metrics.calls=renderer.info.render.calls;metrics.triangles=renderer.info.render.triangles;metrics.frameMs=+(performance.now()-cpuStart).toFixed(1);needsRender=false;
 frameCount++;if(now-fpsStamp>=1500){metrics.fps=Math.round(frameCount*1000/(now-fpsStamp));fpsStamp=now;frameCount=0;}
}
requestAnimationFrame(frame);updateHUD();
if(state.holdingId){holding=world.items.find(it=>it.id===state.holdingId&&!it.done)||null;if(holding){holding.object.visible=false;updateHeld();}}
canvas.addEventListener('webglcontextlost',e=>{e.preventDefault();running=false;$('fatal-error').hidden=false;$('fatal-text').textContent='그래픽 연결이 잠시 끊겼어요. 다시 불러오면 저장한 청소 기록부터 이어갑니다.';});
// A DOM status surface also gives assistive tools a truthful live game state.
const statusNode=document.createElement('output');statusNode.id='game-status';statusNode.hidden=true;document.body.append(statusNode);setInterval(()=>{statusNode.textContent=JSON.stringify({room,tool,holding:holding?.id||null,position:{x:+player.x.toFixed(2),z:+player.z.toFixed(2)},yaw:+yaw.toFixed(3),pitch:+pitch.toFixed(3),target:target?.patch?.id||target?.action?.id||null,running,input:touchMode?'touch':'mouse',mouse:{gain:MOUSE_GAIN,locked:pointerLocked,edge:edgeDirection},contract:state.contract,hints:state.hints,rinsing:{active:rinsing.active,progress:+rinsing.progress.toFixed(2),phase:rinsing.phase},hazards:[{id:glassHazard.id,done:glassHazard.done,x:glassHazard.object.position.x,z:glassHazard.object.position.z}],renderer:{...metrics,mode:state.quality,width:canvas.width,height:canvas.height,postprocessing:!!detailed,shadows:renderer.shadowMap.enabled,batching},progress:Object.fromEntries(['bedroom','kitchen','bathroom'].map(id=>[id,stats(id).percent])),surfaces:patches.map(p=>({id:p.id,x:p.x,y:p.y,z:p.z,progress:+p.progress.toFixed(3),wet:+p.wet.toFixed(2),done:p.done})),objects:world.items.filter(i=>!i.done).map(i=>({id:i.id,x:+i.object.position.x.toFixed(2),z:+i.object.position.z.toFixed(2)}))});},400);
if(navigator.modelContext?.registerTool){try{navigator.modelContext.registerTool({name:'read_home_care_progress',description:'현재 공간, 들고 있는 물건, 청소 도구와 공간별 학습 진행을 읽습니다.',inputSchema:{type:'object',properties:{}},execute:async()=>({content:[{type:'text',text:statusNode.textContent}]})});}catch{}}
